EDX-2781 Add new input for go-lint workflow to install required packages
IOTechSystems/github-action-workflow pull request #2
Opened 2022-06-07 02:26 UTC by jinlinGuan

Signed-off-by: Ginny Guan <ginny@iotechsys.com>

2022-06-07 02:53 UTC, cloudxxx8 approved these changes
LGTM

2022-06-07 02:54 UTC, cloudxxx8 requested changes

2022-06-07 02:54 UTC, cloudxxx8 commented on .github/workflows/reusable-golangci-lint.yml
> +          sudo apt update && sudo apt-get install ${{ inputs.REQUIRED_PACKAGES }}
use `apt` instead of `apt-get`

2022-06-07 03:07 UTC, jinlinGuan commented on .github/workflows/reusable-golangci-lint.yml
> +          sudo apt update && sudo apt-get install ${{ inputs.REQUIRED_PACKAGES }}
updated

2022-06-08 05:47 UTC, cloudxxx8 approved these changes
LGTM

2022-06-08 05:48 UTC, merged